create table Shop_Category(
	id_Shop_Category bigint auto_increment,
	image Nvarchar(80),
    id_Category bigint,
    shop_Name nvarchar(255) not null,
    price nvarchar(255) not null,
    description text,
    priority bit,
    primary key (id_Shop_Category),
    constraint lien_ket_1 foreign key(id_Category) references Category(id_Category)
);
create table Category(
	id_Category bigint auto_increment,
    Categoryl nvarchar(30) not null,
    primary key(id_Category)
);
create table Users(
	id_User bigint auto_increment,
    email nvarchar(50) not null,
    username nvarchar(25) not null,
    password nvarchar(255) not null,
    role bit,
    primary key(id_User)
);
create table orders(
	order_id bigint auto_increment,
	id_Shop_Category bigint,
    id_User bigint,
    quantity int,
    order_date datetime,
    primary key(order_id),
 foreign key(id_Shop_Category) references Shop_Category(id_Shop_Category),
     foreign key(id_User) references Users(id_User)
);
insert into Category(id_Category,Categoryl) values(1,'Laptop');
insert into Category(id_Category,Categoryl) values(2,'Máy tính bảng');
insert into Category(id_Category,Categoryl) values(3,'Điện thoại');
insert into Category(id_Category,Categoryl) values(4,'Phụ kiện');
insert into Shop_Category values(1,'iphone15.png',3,'Iphone 15','34000000','Iphone 15 với những cải tiến so với thế hệ tiền nhiệm như: Nút gạt thay bằng bấm, cổng Lightning thay bằng USB type-c',1);
insert into Shop_Category values(2,'macbook.png',1,'Macbook Air 2023','40000000','Iphone 15 với những cải tiến so với thế hệ tiền nhiệm như: Nút gạt thay bằng bấm, cổng Lightning thay bằng USB type-c',1);
insert into Shop_Category values(3,'airpods.png',4,'Airpods pro 2023','10000000','Iphone 15 với những cải tiến so với thế hệ tiền nhiệm như: Nút gạt thay bằng bấm, cổng Lightning thay bằng USB type-c',1);
insert into Shop_Category values(4,'appleWatch.png',4,'Apple Watch 2023','9000000','Iphone 15 với những cải tiến so với thế hệ tiền nhiệm như: Nút gạt thay bằng bấm, cổng Lightning thay bằng USB type-c',1);
insert into Shop_Category values(5,'oppoFindN3.png',3,'Oppo Find N3','23000000','OPPO Find N3 Flip 5G Hồng được OPPO cho ra mắt chính thức tại thị trường Việt Nam vào tháng 10/2023. Sản phẩm được hãng đầu tư mạnh mẽ về camera với độ phân giải lên đến 50 MP, cấu hình sử dụng chip Dimensity 9200 5G và thiết kế được thay đổi với bản lề gập mở tốt hơn cùng màu hồng sang trọng và nữ tính',0);
insert into Shop_Category values(6,'vivov27e.png',3,'Vivo V27E','6000000','vivo V27e một trong những chiếc điện thoại tầm trung nổi bật của vivo trong năm 2023. Với thiết kế độc đáo và khả năng chụp ảnh - quay phim ấn tượng, vì thế máy đã mang lại cho vivo nhiều niềm tự hào khi ra mắt tại thị trường Việt Nam, hứa hẹn mang đến trải nghiệm tuyệt vời đến với người dùng.',0);
insert into Shop_Category values(7,'xiaomi13lite.png',3,'Xiaomi 13 Lite','9000000','Hãng Xiaomi đã ra mắt mẫu điện thoại Xiaomi 13 Lite 5G, tiếp tục thành công từ dòng flagship Xiaomi 13 series. Được xem là dòng sản phẩm tầm trung, Xiaomi 13 Lite 5G có nhiều điểm nổi bật như sử dụng chipset mới từ Qualcomm và hệ thống camera đáng chú ý trong phân khúc.',0);
insert into Shop_Category values(8,'samsunggalaxys23ultra.png',3,'Samsung Galaxy S23 Ultra','23000000','Samsung Galaxy S23 Ultra 5G 256GB là chiếc smartphone cao cấp nhất của nhà Samsung, sở hữu cấu hình không tưởng với con chip khủng được Qualcomm tối ưu riêng cho dòng Galaxy và camera lên đến 200 MP, xứng danh là chiếc flagship Android được mong đợi nhất trong năm 2023.',0);
insert into Shop_Category values(9,'xiaomi13tpro.png',3,'Xiaomi 13T Pro','8000000','Xiaomi 13T Pro 5G là mẫu máy thuộc phân khúc tầm trung đáng chú ý tại thị trường Việt Nam. Điện thoại ấn tượng nhờ được trang bị chip Dimensity 9200+, camera 50 MP có kèm sự hợp tác với Leica cùng kiểu thiết kế tinh tế đầy sang trọng.',0);
insert into Shop_Category values(20,'samsunggalaxyzflip4.png',3,'Samsung Galaxay ZFlip 4','11000000','Samsung Galaxy Z Flip4 128GB đã chính thức ra mắt thị trường công nghệ, đánh dấu sự trở lại của Samsung trên con đường định hướng người dùng về sự tiện lợi trên những chiếc điện thoại gập. Với độ bền được gia tăng cùng kiểu thiết kế đẹp mắt giúp Flip4 trở thành một trong những tâm điểm sáng giá cho nửa cuối năm 2022.',0);
insert into Shop_Category values(18,'samsunggalaxya34.png',3,'Samsung Galaxay A34','8000000','Samsung Galaxy A34 5G là mẫu điện thoại mới thuộc phân khúc tầm trung được nhà Samsung cho ra mắt vào tháng 03/2023. Với sự kết hợp hoàn hảo giữa vẻ ngoài cuốn hút với cấu hình mạnh mẽ, chiếc máy là sự lựa chọn hoàn hảo đáp ứng tốt nhu cầu sử dụng của đa dạng đối tượng người dùng hiện nay.',0);
insert into Shop_Category values(16,'opporeno10pro.png',3,'Oppo Reno10 Pro','8000000','OPPO Reno10 Pro 5G là một trong những sản phẩm của OPPO được ra mắt trong 2023. Với thiết kế đẹp mắt, màn hình lớn và hiệu năng mạnh mẽ, Reno10 Pro chắc chắn sẽ là lựa chọn đáng cân nhắc dành cho những ai đang tìm kiếm chiếc máy tầm trung để phục vụ tốt mọi nhu cầu.',0);
insert into Shop_Category values(14,'samsunggalaxyzfold5.png',3,'Samsung Galaxay ZFold 5','43000000','Samsung Galaxy Z Fold5 là mẫu điện thoại cao cấp được ra mắt vào tháng 07/2023 với nhiều điểm đáng chú ý như thiết kế gập độc đáo, hiệu năng mạnh mẽ nhờ chip Snapdragon 8 Gen 2 for Galaxy cùng camera quay chụp sắc nét.',0);
insert into Shop_Category values(12,'realme11pro.png',3,'Realme 11 Pro','11000000','realme là một thương hiệu điện thoại thông minh đến từ Trung Quốc, được biết đến với những sản phẩm có thiết kế đẹp, cấu hình mạnh và giá cả hợp lý. Trong đó, có thể kể đến phiên bản realme 11 Pro 5G với một vẻ ngoài đẹp mắt, chất lượng ảnh chụp sắc nét cũng như một hiệu năng đầy mạnh mẽ.',0);
insert into Shop_Category values(10,'aceraspire5gaming.png',1,'Laptop Acer Aspire 5 Gaming','30000000','Mẫu laptop gaming với mức giá tầm trung đến từ thương hiệu Acer vừa được lên kệ tại Thế Giới Di Động, sở hữu hiệu năng mạnh mẽ với con chip Intel Gen 13 dòng H hiệu năng cao, RAM 16 GB, card rời RTX cùng nhiều tính năng hiện đại. Laptop Acer Aspire 5 Gaming A515 58GM 51LB i5 13420H (NX.KQ4SV.002) chắc chắn sẽ mang đến cho bạn những trải nghiệm sử dụng và chiến game giải trí tuyệt vời.',0);
insert into Shop_Category values(11,'aceraspire3a31558589k.png',1,'Laptop Acer Aspire 3 A315-58-589k','10000000','Laptop Acer Aspire 3 A315 58 589K i5 1135G7 (NX.AM0SV.008) thuộc dòng laptop học tập - văn phòng tầm trung được Acer giới thiệu tới người dùng với thông số cấu hình ổn định, ngoại hình ưa nhìn và đặc biệt có mức giá phải chăng.',0);
insert into Shop_Category values(15,'acernitro5.png',1,'Laptop Acer Nitro5','18000000','Laptop Acer Nitro 5 Gaming AN515 57 5669 i5 (NH.QEHSV.001) khơi nguồn mọi cảm hứng game thủ với phong cách thiết kế đậm chất gaming cùng những chuyển động mượt mà với card đồ họa NVIDIA GeForce GTX, mang lại chiến thắng tuyệt đối cho người dùng trên mọi chiến trường ảo.',0);
insert into Shop_Category values(21,'acertravelmatep4.png',1,'Laptop Acer Travel Mate P4','16000000','Laptop Acer TravelMate P4 TMP414 51G 59R6 i5 1135G7 (NX.VP9SV.001) được hoàn thiện với thiết kế tinh tế, nhỏ gọn, kiểu dáng hiện đại cùng hiệu năng ổn định từ CPU Intel i5, RAM 16 GB vận hành êm ái mọi tác vụ văn phòng đến đồ hoạ cơ bản, phù hợp với đối tượng là các bạn sinh viên và người đi làm.',0);
insert into Shop_Category values(13,'dellvostro3520.png',1,'Laptop Dell Vostro 3520','16000000','Laptop Dell Vostro 3520 i3 1215U (V5I3614W1) là một lựa chọn tuyệt vời cho những bạn đang cần tìm một chiếc laptop học tập - văn phòng sở hữu cấu hình ổn định, có khả năng vận hành trơn tru mọi tác vụ thường ngày.',0);
insert into Shop_Category values(17,'dellinspiron153520.png',1,'Laptop Dell Inspiron 15 3520','17000000','Laptop Dell Inspiron 15 3520 i5 1235U (i5U085W11BLU) là phiên bản laptop học tập - văn phòng của nhà Dell khi sở hữu phong cách thiết kế tối giản nhưng không kém phần trẻ trung, bộ vi xử lý Intel Gen 12 và bộ Office bản quyền vĩnh viễn đáp ứng đầy đủ mọi nhu cầu học tập, văn phòng của người dùng.',0);
insert into Shop_Category values(22,'dellinspiron153530.png',1,'Laptop Dell Inspiron 15 3530','19000000','Với mức giá dưới 20 triệu, các bạn sinh viên và nhân viên văn phòng đã có thể sở hữu ngay một mẫu laptop học tập - văn phòng có con chip Intel thế hệ 13 mới nhất, RAM 16 GB cùng nhiều tính năng hiện đại khác. Laptop Dell Inspiron 15 3530 i5 1335U (N5I5791W1) chắc chắn sẽ thỏa mãn đầy đủ mọi nhu cầu của bạn dù làm việc hay giải trí.',0);
insert into Shop_Category values(25,'dellprecision167680.png',1,'Laptop Dell Precision 16 7680','80000000','Laptop Dell Precision 16 7680 i7 13850HX (71024681) sở hữu hàng loạt những thông số khủng như chip Intel dòng HX hiệu năng cao, RAM 32 GB, card rời RTX,... đáp ứng hiệu quả mọi yêu cầu sáng tạo đồ hoạ, phát triển ứng dụng hay kiến trúc. Nay sản phẩm đã được lên kệ với mức giá vô cùng lý tưởng.',0);
insert into Shop_Category values(19,'surfacepro9.png',1,'Laptop Surface Pro9','42000000','Microsoft Surface Pro 9 i7 1255U là dòng sản phẩm mới nhất với sự kết hợp hoàn hảo giữa thiết kế đẳng cấp cùng hiệu suất mạnh mẽ, mang đến cho người dùng một trải nghiệm đa nhiệm, sáng tạo tuyệt vời. Nó không chỉ là một bước tiến vững chắc trong sự phát triển mà còn là sự đổi mới đầy năng động.',0);
insert into Shop_Category values(23,'lggram2023.png',1,'Laptop LG Gram 2023','42000000','Laptop LG gram 2023 i7 1360P (17Z90R-G.AH78A5) sở hữu những thông số cấu hình vượt trội như con chip Intel Gen 13, tốc độ Bus RAM cao, ổ cứng 1 TB, sẽ là sự lựa chọn tuyệt vời để giúp bạn giải quyết mọi công việc.',0);
insert into Shop_Category values(24,'ipadair5m12022.png',2,'Ipad air 5 M1 2022','23000000','iPad Air 5 M1 WiFi 64 GB đã được công bố tại sự kiện Peek Performance diễn ra hôm 9/3 (theo giờ Việt Nam). Năm nay Apple đã có những thay đổi lớn về cả hiệu năng và bổ sung màu sắc mới cho thiết bị.',0);
insert into Shop_Category values(26,'ipadprom22022.png',2,'Ipad pro2 M2 2022','40000000','iPad Pro M2 12.9 inch WiFi 128GB là mẫu tablet mới nhất được nhà Apple phát hành vào tháng 10/2022. Thiết bị được coi là tâm điểm của giới công nghệ tại thời điểm ra mắt khi được trang bị con chip Apple M2 mạnh mẽ, bên cạnh đó sẽ là những ưu điểm khác vượt trội như: hệ điều hành iPadOS 16, quay video 4K với tốc độ khung hình 60 FPS, tần số quét 120 Hz,...',0);
insert into Shop_Category values(30,'ipadair5.png',2,'Ipad Air5 2022','20000000','So với chiếc iPad Air 5 M1 WiFi 64GB thì chiếc iPad Air 5 M1 WiFi Cellular 64GB đã có một điểm khác biệt đáng kể đó là phương thức kết nối khi bạn vừa có thể sử dụng Wifi và mạng di động một cách bình thường nhưng vẫn cho một trải nghiệm rất tuyệt vời.',0);
insert into Shop_Category values(33,'ipadmini6.png',2,'Ipad Mini6 2022','10000000','Sau thời gian dài chờ đợi thì iPad mini 6 WiFi 64GB cũng đã được Apple trình làng với thiết kế vừa quen thuộc vừa mới lạ, máy có nhiều cải tiến trong cấu hình lẫn phần mềm nhằm gia tăng lợi ích sử dụng, mang lại sự hài lòng cao hơn cho người dùng khi lựa chọn.',0);
insert into Shop_Category values(35,'samsunggalaxytabs9.png',2,'Samsung Galaxy Tab S9+','20000000','Tại sự kiện Unpacked 2023 diễn ra tại Hàn Quốc, Samsung đã trình làng mẫu máy tính bảng Samsung Galaxy S thế hệ tiếp theo. Samsung Galaxy Tab S9+ WiFi 256GB sở hữu hiệu năng mạnh mẽ, màn hình hiển thị sắc nét và điểm đặc biệt đây là máy có khả năng kháng nước IP68 cùng nhiều tính năng hấp dẫn khác.',0);
insert into Shop_Category values(29,'samsunggalaxya9.png',2,'Samsung Galaxy Tab A9','7000000','Với giá cả phải chăng, Samsung Galaxy Tab A9+ 5G là một sản phẩm máy tính bảng của Samsung dành cho người dùng muốn sở hữu một thiết bị giải trí cơ bản với màn hình rộng và khả năng kết nối mạng toàn diện để truy cập internet bất kỳ lúc nào và ở bất kỳ đâu.',0);
insert into Shop_Category values(27,'xiaomipad6.png',2,'Xiaomi Pad 6','7000000','Xiaomi tiếp tục định nghĩa công nghệ với sáng kiến mới nhất của mình, Xiaomi Pad 6. Với thiết kế viền kim loại sang trọng, chiếc máy tính bảng này kết hợp sự thanh lịch với hiệu suất mạnh mẽ để đáp ứng tất cả nhu cầu công việc và giải trí của bạn.',0);
insert into Shop_Category values(28,'oppopad2.png',2,'Oppo Pad 2','7000000','OPPO Pad 2 là sản phẩm mới của OPPO trong công cuộc chạy đua công nghệ trên thị trường máy tính bảng. Máy thu hút được khá nhiều sự quan tâm khi trang bị một màn hình lớn, con chip mạnh trong tầm giá cùng một viên pin lớn cho trải nghiệm dài lâu mà ít khi gặp phải gián đoạn.',0);
insert into Shop_Category values(31,'oppopadair.png',2,'Oppo Pad Air','3000000','OPPO Pad Air 128GB là một máy tính bảng đáng chú ý, được thiết kế để đáp ứng nhu cầu đa dạng của người dùng. Với một số thông tin nổi bật như màn hình lớn và hiệu năng ổn định, OPPO Pad Air có thể là lựa chọn tuyệt vời cho những người dùng cần một máy tính bảng đa năng và tiện lợi.',0);
insert into Shop_Category values(32,'lenovotabp11.png',2,'Lenovo Tab 11 Plus','3000000','Máy tính bảng Lenovo Tab P11 Plus sẽ là một lựa chọn để làm việc thay thế laptop khi nhu cầu sử dụng không quá cao, máy được trang bị cấu hình mạnh mẽ, màn hình lớn cùng các chế độ tiện ích đa dạng, đáp ứng được hầu hết nhu cầu của một người sáng tạo với mức giá phải chăng đến từ Lenovo.',0);
insert into Shop_Category values(34,'massteltab10pro.png',2,'Masstel Tab10 Pro','3000000','Máy tính bảng Masstel Tab 10.1 inch Pro là một sản phẩm đến từ Masstel, một thương hiệu công nghệ Việt Nam. Với thiết kế đẹp, chất lượng cao và nhiều tính năng hấp dẫn, máy cũng có một mức giá dễ tiếp cận phù hợp cho mọi người từ học sinh đến những ai muốn tìm một thiết bị phụ để giải trí.',0);
insert into Shop_Category values(42,'applewatchultra2gps.png',4,'Apple Watch Ultra2 GPS','23000000','Apple Watch Ultra 2 GPS + Cellular 49mm viền Titanium dây Ocean là chiếc đồng hồ thông minh của Apple gây được nhiều sự chú ý của giới truyền thông và người yêu công nghệ tại sự kiện Wonderlust năm 2023. Đồng hồ sở hữu vẻ ngoài vừa thời thượng vừa đậm chất thể thao vô cùng độc đáo, các tính năng bên trong cũng có cải tiến hứa hẹn sẽ làm hài lòng sự mong đợi của người dùng.',0);
insert into Shop_Category values(36,'applewatchseries9gps.png',4,'Apple Watch Series 9 GPS','20000000','Siêu phẩm Apple Watch Series 9 GPS + Cellular 45mm viền thép dây thép đã chính thức được trình làng tại sự kiện ra mắt sản phẩm thường niên của Apple vào tháng 9. Đây không chỉ là một trợ thủ đắc lực với nhiều tiện ích thông minh, mà còn là một món phụ kiện sang trọng và thời thượng cho người dùng.',0);
insert into Shop_Category values(40,'applewatchseries8.png',4,'Apple Watch Series 8','15000000','Tại sự kiện Far Out 2022 ngoài iPhone Series thì Apple còn giới thiệu đến giới công nghệ Apple Watch Series 8. Thu hút được sự chú ý của công chúng, vấn đề hiệu năng của thiết bị này cũng được quan tâm đặc biệt. Trong bài viết này mình sẽ đưa ra đánh giá cho sản phẩm Apple Watch Series 8 GPS 41mm viền nhôm dây thể thao sau một thời gian trải nghiệm.',0);
insert into Shop_Category values(37,'samsunggalaxywatch5pro.png',4,'Samsung Galaxy Watch5 Pro','10000000','Samsung đã cho ra mắt chiếc smartwatch có tên gọi là Galaxy Watch5 Pro LTE 45mm. Với những thay đổi về mặt thiết kế, chức năng theo dõi sức khỏe 24/7, đa dạng chế độ thể thao và hệ thống vệ tinh hiện đại hứa hẹn vẫn là sản phẩm làm hài lòng các tín đồ yêu công nghệ.',0);
insert into Shop_Category values(38,'xiaomiwatch2pro.png',4,'Xiaomi Watch2 Pro','6000000','Xiaomi Watch 2 Pro là thế hệ smartwatch thứ 2 sử dụng hệ điều hành Wear OS vừa được Xiaomi trình làng. Với thiết kế sang trọng, hiện đại cùng nhiều tính năng vượt trội, đây hứa hẹn sẽ là người bạn đồng hành lý tưởng cho người dùng trong mọi hoạt động.',0);
insert into Shop_Category values(43,'airpodspro2.png',4,'Tai nghe Airpods Pro 2','5900000','Tai nghe Bluetooth AirPods Pro (2nd Gen) USB-C Charge Apple sở hữu thiết kế mang đậm chất thương hiệu Apple, màu sắc sang trọng, đi cùng nhiều công nghệ cho các iFan: chip Apple H2, chống bụi, chống ồn chủ động,... hứa hẹn mang đến trải nghiệm âm thanh sống động, chinh phục người dùng.',0);
insert into Shop_Category values(39,'samsungtruewireless.png',4,'Tai nghe True Wireless Samsung Galaxy Bud2','4900000','Trong sự kiện Samsung Galaxy Unpacked 2022 diễn ra vào ngày 10/8, Samsung đã cho ra mắt loạt siêu phẩm trong đó có tai nghe Bluetooth True Wireless Samsung Galaxy Buds 2 Pro R510N. Bên cạnh thiết kế cải tiến, Galaxy Buds 2 Pro còn sở hữu nhiều tính năng đáng giá. Đây chắc hẳn chính là món phụ kiện tuyệt vời dành cho các SamFans.',0);
insert into Shop_Category values(41,'sonytruewireless.png',4,'Tai nghe True Wireless Sony','3900000','Tai nghe Bluetooth True Wireless Sony WF-C700N sở hữu thiết kế hiện đại, nhỏ gọn dễ dàng mang theo bất cứ đâu, tai nghe còn trang bị nhiều công nghệ âm thanh hiện đại mang đến cho người dùng những trải nghiệm tuyệt vời.',0);



